<form method="POST" action="/hashlists/edit/"  enctype="multipart/form-data">
    <?=$this->element->id?>
    <table>
        <tr>
            <td>
                <?=$this->element->name->getLabel()?>
            </td>
            <td>
                <?=$this->element->name?>
            </td>
        </tr>
        <tr>
            <td>
                <?=$this->element->alg_id->getLabel()?>
            </td>
            <td>
                <?=$this->element->alg_id?>
            </td>
        </tr>
        <tr>
            <td colspan="2"><?=$this->element->submit?></td>
        </tr>
    </table>
</form>