<br/>
<table class="workTable workFormTable">
    <tr>
        <th><?=$this->translate('L_DICTS_EDIT')?> &quot;<?=$this->dict['name']?>&quot;</th>
    </tr>
    <tr>
        <td><?=$this->form->render()?></td>
    </tr>
    <tr>
        <td class="formHints">

                post_max_size: <?=$this->settings['post_max_size']?><br/>
                upload_max_filesize: <?=$this->settings['upload_max_filesize']?><br/>


        </td>
    </tr>
</table>


