<html>
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" type="text/css" href="/css/style.css?t=<?=time()?>">

        <link rel="stylesheet" href="/js/jquery-ui.min.css">
        <link rel="stylesheet" href="/js/jquery-ui.theme.min.css">
        <link rel="stylesheet" href="/js/jquery-ui.structure.min.css">

        <script src="/js/jquery.js"></script>
        <script src="/js/jquery.cookie.js"></script>
        <script src="/js/jquery-ui.min.js"></script>
        <script src="/js/functions.js?t=<?=time()?>"></script>

        <title>Hash Brute Station</title>

        <script>
            var L_NEW_PRIORITY_VALUE = "<?=$this->translate('L_NEW_PRIORITY_VALUE')?>"
            var L_ALL_WORK_TASKS_START_CONFIRM = "<?=$this->translate('L_ALL_WORK_TASKS_START_CONFIRM')?>"
            var L_ALL_WORK_TASKS_STOP_CONFIRM = "<?=$this->translate('L_ALL_WORK_TASKS_STOP_CONFIRM')?>"
        </script>
    </head>
    <body>
        <center><br>

            <table width=90% cellpadding=0 cellspacing=0>
                <tr>
                    <td class="titleBlock">

                        &nbsp;Hash Brute Station v0.1a
                    </td>
                </tr>
                <tr>
                    <td class="versionBlock">
                        &nbsp;
                    </td>
                </tr>
            </table>

            <table width=90% cellpadding=0 cellspacing=0>
                <tr>
                    <td width=100% class="menuBlock">
                        &nbsp;
                        <a href="/dicts/"><?=$this->translate('L_DICTS')?></a> |
                        <a href="/rules/" ><?=$this->translate('L_RULES')?></a> |
                        <a href="/hashlists/" ><?=$this->translate('L_HASH_LISTS')?></a> |
                        <a href="/tasks/" ><?=$this->translate('L_TASK_TEMPLATES')?></a> |
                        <a href="/work-tasks/" ><?=$this->translate('L_WORK_TASKS')?></a> |
                        <a href="/stats/" ><?=$this->translate('L_STAT')?></a> |
                        <a href="/settings/" ><?=$this->translate('L_SETTINGS')?></a> |
                        <a href="/logs/" ><?=$this->translate('L_LOGS')?></a>
                    </td>
                </tr>
            </table>
            <div id="mainContent">
                <?php echo $this->layout()->content ?>
            </div>

        </center>

    </body>
</html>