<form method="POST" action="/dicts/edit/">
    <?=$this->element->id?>
    <?=$this->element->group_id?>
    <table>
        <tr>
            <td>
                <?=$this->element->name->getLabel()?>
            </td>
            <td>
                <?=$this->element->name?>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <?=$this->element->comment->getLabel()?>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <?=$this->element->comment?>
            </td>
        </tr>
        <tr>
            <td><?=$this->element->submit?></td>
        </tr>
    </table>
</form>