<br/>
<div class="buttonsBlock">
    <button onclick="location.href='/hashlists/add/'"><?=$this->translate('L_HASHLIST_ADD_2')?></button>&nbsp;&nbsp;&nbsp;
</div>
<br/>

<table class="workTable">
    <tr>
        <th colspan="5"><?=$this->translate('L_COMMON_LISTS')?></th>
    </tr>
    <tr>
        <th><?=$this->translate('L_LIST_NAME')?></th>
        <th><?=$this->translate('L_CRACKED')?></th>
        <th><?=$this->translate('L_NON_CRACKED')?></th>
        <th><?=$this->translate('L_ALG')?></th>
        <th><?=$this->translate('L_STATUS')?></th>
    </tr>
    <?foreach ($this->common_list as $hashlist):?>
        <tr class="highlighted-hashlists">
            <td><?=$hashlist->name?></td>
            <td id="hashlist<?=$hashlist->id?>cracked">
                <?=$hashlist->getCounts()['cracked']?> (<?=$hashlist->getCounts()['cracked_percents']?>%)
            </td>
            <td id="hashlist<?=$hashlist->id?>not_cracked">
                <?=$hashlist->getCounts()['not_cracked']?> (<?=$hashlist->getCounts()['not_cracked_percents']?>%)
            </td>
            <td><?=$hashlist->getAlg()?></td>
            <td id="hashlist<?=$hashlist->id?>status"><?=$this->translate('L_HASHLIST_STATUS_' . strtoupper($hashlist->status))?></td>
        </tr>
    <?endforeach;?>
</table>

<br/><br/>

<table class="workTable">
    <tr>
        <th colspan="11"><?=$this->translate('L_USERS_LISTS')?></th>
    </tr>
    <tr>
        <th><?=$this->translate('L_LIST_NAME')?></th>
        <th><?=$this->translate('L_CRACKED')?></th>
        <th><?=$this->translate('L_NON_CRACKED')?></th>
        <th><?=$this->translate('L_ALG')?></th>
        <th><?=$this->translate('L_STATUS')?></th>
        <th colspan="6"><?=$this->translate('L_ACTIONS')?></th>
    </tr>
<?foreach ($this->list as $hashlist):?>
    <tr class="highlighted-hashlists">
        <td><?=$hashlist->name?></td>
        <td id="hashlist<?=$hashlist->id?>cracked">
            <?=$hashlist->getCounts()['cracked']?> (<?=$hashlist->getCounts()['cracked_percents']?>%)
        </td>
        <td id="hashlist<?=$hashlist->id?>not_cracked">
            <?=$hashlist->getCounts()['not_cracked']?> (<?=$hashlist->getCounts()['not_cracked_percents']?>%)
        </td>
        <td><?=$hashlist->getAlg()?></td>
        <td id="hashlist<?=$hashlist->id?>status"><?=$this->translate('L_HASHLIST_STATUS_' . strtoupper($hashlist->status))?></td>

        <td><a href="/hashlists/edit/id/<?=$hashlist->id?>/"><?=$this->translate('L_EDIT_2')?></a></td>
        <td><a id="deleteHashlist<?=$hashlist->id?>" href="/hashlists/delete/id/<?=$hashlist->id?>/" onclick="return confirm('<?=$this->translate('L_WANT_DELETE')?> <?=$hashlist->name?>?')"><?=$this->translate('L_DELETE')?></a></td>
        <td><a href="/hashlists/import/id/<?=$hashlist->id?>/"><?=$this->translate('L_LOAD_OUT')?></a></td>
        <td><a href="/hashlists/in/id/<?=$hashlist->id?>/"><?=$this->translate('L_ADD')?></a></td>
        <td>
        <?if(strlen(trim($hashlist->errors))):?>
            <a href="/hashlists/errors/id/<?=$hashlist->id?>/"><?=$this->translate('L_ERRORS')?> (<?=substr_count($hashlist->errors, "\n")?>)</a>
        <?else:?>
            <?=$this->translate('L_NO_ERRORS')?>
        <?endif?>
        </td>
    </tr>
<?endforeach;?>
</table>
<script>
    var hlInterval = setInterval(refreshHashlistsData, 2000)
</script>