<br/>
<div class="buttonsBlock">
    <button onclick="location.href='/hashlists/add/'"><?=$this->translate('L_HASHLIST_ADD_2')?></button>&nbsp;&nbsp;&nbsp;
</div>
<br/>
<table class="workTable">
    <tr>
        <th><?=$this->translate('L_LIST_NAME')?></th>
        <th><?=$this->translate('L_CRACKED')?></th>
        <th><?=$this->translate('L_NON_CRACKED')?></th>
        <th><?=$this->translate('L_ALG')?></th>
        <th colspan="6"><?=$this->translate('L_ACTIONS')?></th>
    </tr>
<?foreach ($this->list as $hashlist):?>
    <tr>
        <td><?=$hashlist->name?></td>
        <td>
            <?=$hashlist->getCounts()['cracked']?>
            <?if ($hashlist->getCounts()['not_cracked']+$hashlist->getCounts()['cracked']):?>
            (<?=
                round(
                    $hashlist->getCounts()['cracked'] / ($hashlist->getCounts()['not_cracked']+$hashlist->getCounts()['cracked']) * 100,
                    0
                )
            ?>%
            )
            <?endif?>
        </td>
        <td><?=$hashlist->getCounts()['not_cracked']?></td>
        <td><?=$hashlist->getAlg()?></td>

        <td><a href="/hashlists/edit/id/<?=$hashlist->id?>/"><?=$this->translate('L_EDIT_2')?></a></td>
        <td><a id="deleteHashlist<?=$hashlist->id?>" href="/hashlists/delete/id/<?=$hashlist->id?>/" onclick="return confirm('<?=$this->translate('L_WANT_DELETE')?> <?=$hashlist->name?>?')"><?=$this->translate('L_DELETE')?></a></td>
        <td><a href="/hashlists/import/id/<?=$hashlist->id?>/"><?=$this->translate('L_LOAD_OUT')?></a></td>
        <td><a href="/hashlists/in/id/<?=$hashlist->id?>/"><?=$this->translate('L_ADD')?></a></td>
        <td>
        <?if(strlen(trim($hashlist->errors))):?>
            <a href="/hashlists/errors/id/<?=$hashlist->id?>/"><?=$this->translate('L_ERRORS')?> (<?=substr_count($hashlist->errors, "\n")?>)</a>
        <?else:?>
            <?=$this->translate('L_NO_ERRORS')?>
        <?endif?>
        </td>
    </tr>
<?endforeach;?>
</table>