<form method="POST" action="/rules/add/"  enctype="multipart/form-data">
    <table>
        <tr>
            <td>
                <?=$this->element->file->getLabel()?>
            </td>
            <td>
                <?=$this->element->file?>
            </td>
        </tr>
        <tr>
            <td>
                <?=$this->element->name->getLabel()?>
            </td>
            <td>
                <?=$this->element->name?>
            </td>
        </tr>
        <tr>
            <td colspan="2"><?=$this->element->submit?></td>
        </tr>
    </table>
</form>
